language: node_js
node_js:
  - '0.10'
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: knjcode@gmail.com
  password:
    secure: W6xwHsyzcTra9OyIG4QJx8dSH2al9We7anzfd/s2Q8yfLrYvtUG2ikMeusrudlLVghHyMo5RSepGBHeDm1i5yihvlCBfoQFoeB4XLFXwZp1wrNChoB50BejY4gU0XmBMBJUZ5sDJbrPy9GzfH46l5VCZQ+V5ws5x4Loo3cth/ds=
  organization: prototype-cafe
  space: production
  on:
    repo: prototype-cafe/cafeo
    branch: master
sudo: required
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: T/aOSvbKnMZRRmzbshRzMd9t40/zEx/UJUxTNvB8gfSb6l+VLdica3XznDlZcOuB9GlOMVaUXGuV/fUUcaHXH3ecqQ5T5wF93srSl/+O4QLMSj0XYp6Vhnl3VlpEbBzPcuadl7OkzRjJiQDFzZtYnPFfY7rK7TCkXimFR+nTAYk=
